# Site settings
title: SCIENCE AND TECHNOLOGY FOR CLIMATE ACTION
email: dasol.kim@seoultech.ac.kr
baseurl: "/grayscale-theme"
url: https://dasol-st.github.io
description: "Building a Sustainable Future for the Next Generation"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: https://dasol-st.github.io/ccrl/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: researchgate
    url: https://www.researchgate.net/profile/Dasol-Kim-13?ev=hdr_xprf
  - title: linkedin
    url: https://www.linkedin.com/in/dasol-kim-9a9243281/

# Build settings
markdown: kramdown
permalink: pretty
